version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      frontend:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules # <---- this enables a much faster start/reload
    environment: 
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading